name: maplinrobotarm # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Make the Maplin Robot Arm move # 79 char long summary
description: |
  This Snap gives you a web interface to control a Maplin Robot Arm.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    robot:
        command: bin/maplinrobotarm
        plugs: [network-bind, network, serial]
    web:
        command: bin/maplinrobotarmweb
        daemon: simple
        plugs: [network-bind, network]
parts:
 robot:
  plugin: go
  source: src
  stage-packages:
    - libusb-1.0-0
  go-packages:
    - github.com/fromkeith/gorest
    - github.com/kylelemons/gousb/usb
    - github.com/go-martini/martini
 move:
  plugin: dump
  source: .
  organize:
    maplinrobotarm: bin/maplinrobotarm
    maplinrobotarmweb: bin/maplinrobotarmweb
  #snap:
  #  - .
  #filesets:
  #  all: [ . ]
